### ISSUE TITLE
Mittens Deadlock error

### ISSUE THREAD

**Issue by nitinatgh** [ExpediaGroup/mittens#366]
**Describe the bug**

A deadlock is been thrown by Mittens, not sure when or why this is occurring, but in EG we have seen a few occasions of this occurrence.

```
2024/05/07 10:48:16 🟢 Warmup completed
2024/05/07 10:48:16 🛑 Warm up finished but no requests were sent 🙁
2024/05/07 10:48:16 Writing file: ready
2024/05/07 10:48:16 Wrote file: ready
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [select (no cases)]:
mittens/cmd.block(...)
        /mittens/cmd/root.go:141
mittens/cmd.RunCmdRoot()
        /mittens/cmd/root.go:44 +0x47
main.main()
        /mittens/main.go:23 +0x1c
```

Version: `1.45.0`

Understand there is new versions, but wanted to capture this bug in case it does happen for new ones. Not sure how many are using the latest version. But will keep an eye open and will try to dig in a bit more for occurrences.

**To Reproduce**

Unable too

**Expected behavior**

No deadlock should occur.

**Additional context**

**Comment by gsi85** [comment]
We hit this too. Root cause: after warm-up, `block()` parks the main goroutine on a bare `select {}` to "run forever". Once every other goroutine has wound down and the process goes fully idle, Go's runtime treats the empty select as a deadlock and aborts with `all goroutines are asleep - deadlock!` — exactly the trace above. It surfaces when the binary is built with a newer Go toolchain (1.22+); older ones only lengthened the fuse, which is why released images haven't shown it yet.

Opened #405 to fix it: wait on `SIGINT`/`SIGTERM` instead of `select {}`. A signal receive is externally wakeable, so the deadlock detector never fires, and it also restores graceful shutdown on termination. `-exit-after-warmup` behaviour is unchanged. CI is green and unit tests are included — a maintainer review would be much appreciated 🙏
