### ISSUE TITLE
gRPC concurrency is broken

### ISSUE THREAD

**Issue by nikos912000** [ExpediaGroup/mittens#89]
**Describe the bug**

Setting concurrency to > 1 and sending gRPC requests leads to panic with the following message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x16211d9]

goroutine 7 [running]:
github.com/fullstorydev/grpcurl.InvokeRPC(0x1912700, 0xc0001e68b8, 0x0, 0x0, 0x1905800, 0x0, 0x7ffeefbff91b, 0x29, 0x0, 0x0, ...)
	/Users/nkatirtzis/go/pkg/mod/github.com/fullstorydev/grpcurl@v1.5.1/invoke.go:96 +0x199
mittens/pkg/grpc.(*Client).Request(0xc00009af00, 0x7ffeefbff91b, 0x29, 0x7ffeefbff945, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nkatirtzis/projects/mittens/pkg/grpc/client.go:104 +0x4bb
mittens/pkg/warmup.Warmup.GrpcWarmupWorker(0xc000342960, 0xc000351b00, 0x15, 0xc00033da00, 0xe, 0xffffffffffffffff, 0x1, 0xc00033da10, 0x183e580, 0x0, ...)
	/Users/nkatirtzis/projects/mittens/pkg/warmup/warmup.go:69 +0x159
created by mittens/cmd.runWarmup
	/Users/nkatirtzis/projects/mittens/cmd/root.go:114 +0x42e
```

**To Reproduce**
Set concurrency=2 and include gRPC requests.

**Expected behavior**
No panic. gRPC requests sent successfully.

**Additional context**

The regression was first noticed as part of [this](https://github.com/ExpediaGroup/mittens/commit/83ddb31296a68dc8e9ede9f283448d12e2f0cc7b) commit. In fact, the commit made concurrency work, but the [sync.Once.Do](https://github.com/ExpediaGroup/mittens/blob/f628b727ea8d6511fc04792916940888076d17f4/pkg/grpc/client.go#L88-L90) call causes issues. I tried removing it and establish the connection to the gRPC server on every request and that seems to work.

We may need to extract that call and do it before spinning up the coroutines in [runWarmup](https://github.com/ExpediaGroup/mittens/blob/35541b594ce16c6e1f6834f6855f6ad31ea59e84/cmd/root.go#L99).

**Comment by nikos912000** [comment]
Fixed as part of [1.13](https://github.com/ExpediaGroup/mittens/releases/tag/v1.13) release.
